# Generated by Django 4.2.5 on 2023-10-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow_status',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
